export const SCI_TECH_LAB_CONFIG = {
  companyNameVi: "CÔNG TY CỔ PHẦN SCI-TECH",
  companyNameEn: "SCI-TECH JOINT STOCK COMPANY",
  coverLocationLabel: "TP. Hồ Chí Minh",
  addressLines: [
    "Lô II, Đường số 1, Nhóm CN 2,",
    "Khu công nghiệp Tân Bình,",
    "Phường Tây Thạnh,",
    "Thành phố Hồ Chí Minh,",
    "Việt Nam",
  ],
  footerAddressLines: [
    "Lô II, Đường số 1,",
    "Nhóm CN 2,",
    "Khu công nghiệp Tân Bình,",
    "Phường Tây Thạnh,",
    "TP. Hồ Chí Minh,",
    "Việt Nam",
  ],
  taxCode: "0318177785",
  phone: "0931004818",
  website: process.env.SCI_TECH_WEBSITE?.trim() || "(để cấu hình)",
  email: process.env.SCI_TECH_EMAIL?.trim() || "(để cấu hình)",
  logoPath: "/sci-tech-logo.png",
  documentCode: "LIMS-TR-FM-001",
  documentVersion: "01",
  generatedBy: "Generated by Lab Inventory LIMS",
  colors: {
    primary: "#2D5A9E",
    secondary: "#55C595",
    border: "#CCCCCC",
    text: "#111111",
  },
  accreditation: {
    enabled: process.env.SCI_TECH_ACCREDITATION_ENABLED === "true",
    number: process.env.SCI_TECH_ACCREDITATION_NO?.trim() || "",
  },
  clientInfoDisclaimer: {
    en: "The above information is submitted and identified by the client/applicant.",
    vi: "Các thông tin trên được cung cấp và nhận dạng bởi khách hàng/người yêu cầu.",
  },
  legalDisclaimer:
    "Unless otherwise stated, the results shown in this report refer only to the sample(s) tested. " +
    "This document shall not be reproduced except in full without the written approval of SCI-TECH. " +
    "SCI-TECH accepts no liability for any use of this report outside its intended purpose. " +
    "The testing was performed under SCI-TECH's standard terms and conditions unless otherwise agreed in writing.",
  isoNotes: [
    {
      en: "Test results are valid only for the sample(s) tested.",
      vi: "Kết quả thử nghiệm chỉ có giá trị đối với mẫu được thử nghiệm.",
    },
    {
      en: "This report shall not be reproduced in part without written approval of SCI-TECH.",
      vi: "Không được sao chép một phần báo cáo nếu không có sự đồng ý bằng văn bản của SCI-TECH.",
    },
    {
      en: "Tests were performed according to the methods stated in this report.",
      vi: "Các phép thử được thực hiện theo phương pháp ghi trong báo cáo.",
    },
    {
      en: "Measurement uncertainty is provided upon client request or when required for conformity assessment.",
      vi: "Độ không đảm bảo đo được cung cấp theo yêu cầu của khách hàng hoặc khi cần cho đánh giá sự phù hợp.",
    },
    {
      en: "Decision rules apply when Pass/Fail conclusions are reported.",
      vi: "Quy tắc ra quyết định được áp dụng khi có kết luận Đạt/Không đạt.",
    },
  ],
  technicalNotes: [
    {
      en: "LOD (Limit of Detection): the lowest concentration of an analyte that can be detected but not necessarily quantified.",
      vi: "LOD (Giới hạn phát hiện): nồng độ thấp nhất của chất phân tích có thể phát hiện nhưng chưa nhất thiết định lượng được.",
    },
    {
      en: "LOQ (Limit of Quantitation): the lowest concentration of an analyte that can be quantified with acceptable accuracy and precision.",
      vi: "LOQ (Giới hạn định lượng): nồng độ thấp nhất của chất phân tích có thể định lượng với độ chính xác và độ lặp lại chấp nhận được.",
    },
    {
      en: "Unless otherwise specified, the latest applicable versions of referenced standards and methods were used.",
      vi: "Trừ khi có quy định khác, các phiên bản mới nhất của tiêu chuẩn và phương pháp tham chiếu được áp dụng.",
    },
    {
      en: "Values below LOD are reported as not detected unless otherwise stated.",
      vi: "Giá trị dưới LOD được báo cáo là không phát hiện trừ khi có quy định khác.",
    },
  ],
  defaultRemarks:
    "The above results apply only to the sample(s) submitted for testing. / Các kết quả trên chỉ áp dụng cho mẫu được gửi thử nghiệm.",
  conclusionDisclaimer:
    "The laboratory reports analytical results only and does not provide a statement of conformity unless explicitly requested. / " +
    "Phòng thử nghiệm chỉ báo cáo kết quả phân tích và không đưa ra kết luận phù hợp trừ khi được yêu cầu rõ ràng.",
  testsRequestedFallback: {
    en: "As applicant's requirement",
    vi: "Theo yêu cầu của khách hàng",
  },
  sampledByFallback: {
    en: "Client",
    vi: "Khách hàng",
  },
  testResultsReferNext: {
    en: "Please refer to the next page(s).",
    vi: "Vui lòng tham khảo trang sau.",
  },
} as const;

export type BilingualText = { en: string; vi: string };
