import {
  AlertItem,
  AuditLog,
  Chemical,
  InventoryItem,
  Solution,
  Standard,
  Transaction,
} from "@/types";

export const chemicals: Chemical[] = [
  {
    id: "CHEM-0001",
    code: "CHEM-0001",
    name: "Methanol",
    cas: "67-56-1",
    lot: "MET-2401",
    grade: "HPLC",
    location: "A1-03",
    quantity: 18,
    unit: "L",
    expiryDate: "2026-08-18",
    status: "Available",
  },
  {
    id: "CHEM-0002",
    code: "CHEM-0002",
    name: "Acetonitrile",
    cas: "75-05-8",
    lot: "ACN-2405",
    grade: "LC-MS",
    location: "A1-04",
    quantity: 4,
    unit: "L",
    expiryDate: "2026-07-02",
    status: "Low Stock",
  },
  {
    id: "CHEM-0003",
    code: "CHEM-0003",
    name: "Hydrochloric acid",
    cas: "7647-01-0",
    lot: "HCL-2309",
    grade: "ACS",
    location: "B2-01",
    quantity: 22,
    unit: "L",
    expiryDate: "2026-09-29",
    status: "Available",
  },
  {
    id: "CHEM-0004",
    code: "CHEM-0004",
    name: "Sodium hydroxide",
    cas: "1310-73-2",
    lot: "NAOH-2402",
    grade: "Pellet",
    location: "B2-03",
    quantity: 7,
    unit: "kg",
    expiryDate: "2026-06-30",
    status: "Low Stock",
  },
  {
    id: "CHEM-0005",
    code: "CHEM-0005",
    name: "Sulfuric acid",
    cas: "7664-93-9",
    lot: "H2SO4-2308",
    grade: "Analytical",
    location: "B3-02",
    quantity: 3,
    unit: "L",
    expiryDate: "2026-06-21",
    status: "Expired",
  },
  {
    id: "CHEM-0006",
    code: "CHEM-0006",
    name: "Toluene",
    cas: "108-88-3",
    lot: "TOL-2407",
    grade: "HPLC",
    location: "A2-05",
    quantity: 11,
    unit: "L",
    expiryDate: "2026-10-10",
    status: "Available",
  },
  {
    id: "CHEM-0007",
    code: "CHEM-0007",
    name: "Potassium dihydrogen phosphate",
    cas: "7778-77-0",
    lot: "KH2PO4-2404",
    grade: "Reagent",
    location: "C1-02",
    quantity: 5,
    unit: "kg",
    expiryDate: "2026-07-18",
    status: "Pending Disposal",
  },
  {
    id: "CHEM-0008",
    code: "CHEM-0008",
    name: "Water HPLC grade",
    cas: "7732-18-5",
    lot: "H2O-2406",
    grade: "HPLC",
    location: "A1-01",
    quantity: 30,
    unit: "L",
    expiryDate: "2026-11-30",
    status: "Available",
  },
];

export const standards: Standard[] = [
  {
    id: "STD-0001",
    code: "STD-0001",
    name: "Caffeine CRM",
    type: "CRM",
    lot: "CAF-2301",
    purity: "99.98%",
    uncertainty: "0.03%",
    certificateExpiry: "2026-12-15",
    afterOpenExpiry: "2026-07-15",
    location: "C2-04",
    status: "Approved",
  },
  {
    id: "STD-0002",
    code: "STD-0002",
    name: "Benzoic Acid CRM",
    type: "CRM",
    lot: "BEN-2304",
    purity: "99.95%",
    uncertainty: "0.04%",
    certificateExpiry: "2026-09-12",
    afterOpenExpiry: "2026-08-01",
    location: "C2-05",
    status: "Approved",
  },
  {
    id: "STD-0003",
    code: "STD-0003",
    name: "Sodium Chloride RM",
    type: "RM",
    lot: "NaCl-2403",
    purity: "99.90%",
    uncertainty: "0.02%",
    certificateExpiry: "2027-01-10",
    afterOpenExpiry: "2026-07-20",
    location: "C3-02",
    status: "In Use",
  },
  {
    id: "STD-0004",
    code: "STD-0004",
    name: "Nickel Standard 1000 mg/L",
    type: "Working",
    lot: "NI-2408",
    purity: "99.50%",
    uncertainty: "0.5%",
    certificateExpiry: "2026-08-05",
    afterOpenExpiry: "2026-06-28",
    location: "D1-01",
    status: "Pending Review",
  },
  {
    id: "STD-0005",
    code: "STD-0005",
    name: "CO2 Calibration Gas",
    type: "Working",
    lot: "CO2-2409",
    purity: "99.999%",
    uncertainty: "0.01%",
    certificateExpiry: "2026-07-22",
    afterOpenExpiry: "2026-06-25",
    location: "D1-03",
    status: "Expired",
  },
  {
    id: "STD-0006",
    code: "STD-0006",
    name: "Ruthenium Standard",
    type: "RM",
    lot: "RU-2410",
    purity: "99.96%",
    uncertainty: "0.05%",
    certificateExpiry: "2027-02-18",
    afterOpenExpiry: "2026-09-16",
    location: "C3-05",
    status: "Approved",
  },
];

export const solutions: Solution[] = [
  {
    id: "SOL-0001",
    code: "SOL-0001",
    name: "0.1 N HCl Solution",
    concentration: "0.1 N",
    preparedFrom: "STD-0001",
    preparedBy: "D. Tran",
    preparedDate: "2026-06-01",
    expiryDate: "2026-06-24",
    status: "Pending Approval",
  },
  {
    id: "SOL-0002",
    code: "SOL-0002",
    name: "10 ppm Caffeine Standard",
    concentration: "10 ppm",
    preparedFrom: "STD-0002",
    preparedBy: "N. Pham",
    preparedDate: "2026-06-10",
    expiryDate: "2026-07-10",
    status: "New",
  },
  {
    id: "SOL-0003",
    code: "SOL-0003",
    name: "50 mM Phosphate Buffer",
    concentration: "50 mM",
    preparedFrom: "STD-0007",
    preparedBy: "T. Nguyen",
    preparedDate: "2026-05-28",
    expiryDate: "2026-07-05",
    status: "In Use",
  },
  {
    id: "SOL-0004",
    code: "SOL-0004",
    name: "1 M NaOH Working Solution",
    concentration: "1 M",
    preparedFrom: "STD-0003",
    preparedBy: "L. Vo",
    preparedDate: "2026-06-12",
    expiryDate: "2026-08-12",
    status: "In Use",
  },
  {
    id: "SOL-0005",
    code: "SOL-0005",
    name: "100 ppb Nickel Standard",
    concentration: "100 ppb",
    preparedFrom: "STD-0004",
    preparedBy: "H. Le",
    preparedDate: "2026-06-15",
    expiryDate: "2026-06-20",
    status: "Expired",
  },
];

export const transactions: Transaction[] = [
  {
    id: "TRX-001",
    date: "2026-06-16",
    type: "IN",
    itemCode: "CHEM-0001",
    itemName: "Methanol",
    quantity: 5,
    unit: "L",
    performedBy: "A. Minh",
    purpose: "New shipment receipt",
  },
  {
    id: "TRX-002",
    date: "2026-06-15",
    type: "OUT",
    itemCode: "CHEM-0002",
    itemName: "Acetonitrile",
    quantity: 2,
    unit: "L",
    performedBy: "B. Quang",
    purpose: "HPLC run",
  },
  {
    id: "TRX-003",
    date: "2026-06-14",
    type: "USE",
    itemCode: "STD-0001",
    itemName: "Caffeine CRM",
    quantity: 1,
    unit: "mL",
    performedBy: "Q. Hoa",
    purpose: "Calibration",
  },
  {
    id: "TRX-004",
    date: "2026-06-13",
    type: "DISPOSE",
    itemCode: "CHEM-0005",
    itemName: "Sulfuric acid",
    quantity: 1,
    unit: "L",
    performedBy: "M. Kieu",
    purpose: "Expired reagent disposal",
  },
  {
    id: "TRX-005",
    date: "2026-06-12",
    type: "IN",
    itemCode: "CHEM-0008",
    itemName: "Water HPLC grade",
    quantity: 20,
    unit: "L",
    performedBy: "P. Huy",
    purpose: "Refill stock",
  },
  {
    id: "TRX-006",
    date: "2026-06-11",
    type: "OUT",
    itemCode: "SOL-0003",
    itemName: "50 mM Phosphate Buffer",
    quantity: 3,
    unit: "mL",
    performedBy: "D. Son",
    purpose: "Sample preparation",
  },
  {
    id: "TRX-007",
    date: "2026-06-10",
    type: "USE",
    itemCode: "CHEM-0006",
    itemName: "Toluene",
    quantity: 4,
    unit: "L",
    performedBy: "V. Lam",
    purpose: "Cleaning solvent",
  },
  {
    id: "TRX-008",
    date: "2026-06-09",
    type: "IN",
    itemCode: "CHEM-0007",
    itemName: "Potassium dihydrogen phosphate",
    quantity: 8,
    unit: "kg",
    performedBy: "N. Anh",
    purpose: "Buffer preparation",
  },
  {
    id: "TRX-009",
    date: "2026-06-08",
    type: "OUT",
    itemCode: "CHEM-0004",
    itemName: "Sodium hydroxide",
    quantity: 1,
    unit: "kg",
    performedBy: "K. Hoa",
    purpose: "Neutralization",
  },
  {
    id: "TRX-010",
    date: "2026-06-07",
    type: "USE",
    itemCode: "STD-0003",
    itemName: "Sodium Chloride RM",
    quantity: 2,
    unit: "g",
    performedBy: "L. Tuan",
    purpose: "Method validation",
  },
];

export const inventoryItems: InventoryItem[] = [
  {
    id: "INV-001",
    code: "CHEM-0001",
    name: "Methanol",
    expectedQty: 20,
    countedQty: 18,
    difference: -2,
    location: "A1-03",
    status: "Missing",
  },
  {
    id: "INV-002",
    code: "CHEM-0003",
    name: "Hydrochloric acid",
    expectedQty: 25,
    countedQty: 22,
    difference: -3,
    location: "B2-01",
    status: "Missing",
  },
  {
    id: "INV-003",
    code: "CHEM-0008",
    name: "Water HPLC grade",
    expectedQty: 30,
    countedQty: 30,
    difference: 0,
    location: "A1-01",
    status: "Matched",
  },
  {
    id: "INV-004",
    code: "STD-0002",
    name: "Benzoic Acid CRM",
    expectedQty: 4,
    countedQty: 5,
    difference: 1,
    location: "C2-05",
    status: "Over",
  },
  {
    id: "INV-005",
    code: "STD-0005",
    name: "CO2 Calibration Gas",
    expectedQty: 2,
    countedQty: 1,
    difference: -1,
    location: "D1-03",
    status: "Expired",
  },
  {
    id: "INV-006",
    code: "CHEM-0006",
    name: "Toluene",
    expectedQty: 12,
    countedQty: 11,
    difference: -1,
    location: "A2-05",
    status: "Wrong Location",
  },
];

export const alerts: AlertItem[] = [
  {
    id: "ALT-001",
    title: "Hết hạn trong 30 ngày",
    description: "Sulfuric acid sẽ hết hạn trong 3 ngày.",
    severity: "Critical",
    type: "Expiry",
    date: "2026-06-18",
    itemCode: "CHEM-0005",
    itemRoute: "/chemicals",
  },
  {
    id: "ALT-002",
    title: "Tồn kho thấp",
    description: "Acetonitrile còn 4 L, dưới mức cảnh báo.",
    severity: "Warning",
    type: "Low Stock",
    date: "2026-06-17",
    itemCode: "CHEM-0002",
    itemRoute: "/chemicals",
  },
  {
    id: "ALT-003",
    title: "Thiếu COA",
    description: "Lot CO2-2409 chưa có COA đính kèm.",
    severity: "Warning",
    type: "Missing COA",
    date: "2026-06-16",
    itemCode: "STD-0005",
    itemRoute: "/standards",
  },
  {
    id: "ALT-004",
    title: "Thiếu SDS",
    description: "Dung dịch 0.1 N HCl đang thiếu SDS.",
    severity: "Info",
    type: "Missing SDS",
    date: "2026-06-16",
    itemCode: "SOL-0001",
    itemRoute: "/solutions",
  },
  {
    id: "ALT-005",
    title: "Chờ huỷ",
    description: "Khối lượng 2 kg potassium dihydrogen phosphate đang chờ xử lý huỷ.",
    severity: "Info",
    type: "Pending Disposal",
    date: "2026-06-15",
    itemCode: "CHEM-0007",
    itemRoute: "/chemicals",
  },
  {
    id: "ALT-006",
    title: "Hết hạn trong 30 ngày",
    description: "CO2 calibration gas hết hạn sau 7 ngày.",
    severity: "Critical",
    type: "Expiry",
    date: "2026-06-15",
    itemCode: "STD-0005",
    itemRoute: "/standards",
  },
  {
    id: "ALT-007",
    title: "Tồn kho thấp",
    description: "Sodium hydroxide còn 7 kg.",
    severity: "Warning",
    type: "Low Stock",
    date: "2026-06-14",
    itemCode: "CHEM-0004",
    itemRoute: "/chemicals",
  },
  {
    id: "ALT-008",
    title: "Thiếu SDS",
    description: "Lot TOL-2407 thiếu SDS cập nhật.",
    severity: "Info",
    type: "Missing SDS",
    date: "2026-06-13",
    itemCode: "CHEM-0006",
    itemRoute: "/chemicals",
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: "AUD-001",
    time: "2026-06-18 08:15",
    user: "QC Analyst",
    action: "Updated",
    object: "CHEM-0002",
    before: "Qty 5 L",
    after: "Qty 4 L",
  },
  {
    id: "AUD-002",
    time: "2026-06-18 07:40",
    user: "Lab Manager",
    action: "Approved",
    object: "SOL-0001",
    before: "Pending approval",
    after: "Approved",
  },
  {
    id: "AUD-003",
    time: "2026-06-17 16:55",
    user: "A. Minh",
    action: "Created",
    object: "TRX-001",
    before: "-",
    after: "IN 5 L Methanol",
  },
  {
    id: "AUD-004",
    time: "2026-06-17 15:20",
    user: "Q. Hoa",
    action: "Uploaded",
    object: "STD-0001",
    before: "No COA",
    after: "COA attached",
  },
  {
    id: "AUD-005",
    time: "2026-06-17 12:10",
    user: "D. Son",
    action: "Reassigned",
    object: "CHEM-0007",
    before: "Shelf C1-02",
    after: "Shelf C1-04",
  },
  {
    id: "AUD-006",
    time: "2026-06-17 09:45",
    user: "N. Anh",
    action: "Disposed",
    object: "CHEM-0005",
    before: "Stored",
    after: "Disposed",
  },
  {
    id: "AUD-007",
    time: "2026-06-16 18:30",
    user: "K. Hoa",
    action: "Adjusted",
    object: "INV-001",
    before: "Expected 20",
    after: "Counted 18",
  },
  {
    id: "AUD-008",
    time: "2026-06-16 17:15",
    user: "P. Huy",
    action: "Prepared",
    object: "SOL-0002",
    before: "-",
    after: "10 ppm standard",
  },
  {
    id: "AUD-009",
    time: "2026-06-16 14:05",
    user: "L. Tuan",
    action: "Reviewed",
    object: "STD-0004",
    before: "Pending review",
    after: "Approved",
  },
  {
    id: "AUD-010",
    time: "2026-06-15 10:00",
    user: "QC Analyst",
    action: "Created",
    object: "INV-006",
    before: "-",
    after: "Cycle count started",
  },
];
