import type { CompatibilityOperandKind, CompatibilityRuleType } from "@/types/chem-info";
import { deriveRuleType } from "@/lib/services/chem-info/compatibility-engine";

export type CompatibilityRuleSeed = {
  code: string;
  operandAKind: CompatibilityOperandKind;
  operandAValue: string;
  operandBKind: CompatibilityOperandKind;
  operandBValue: string;
  categoryALabel: string;
  categoryBLabel: string;
  severity: "critical" | "high" | "medium" | "low";
  title: string;
  message: string;
  storageGuidance: string;
  examples: string[];
};

function rule(
  seed: CompatibilityRuleSeed & { ruleType?: CompatibilityRuleType },
): CompatibilityRuleSeed & { ruleType: CompatibilityRuleType; categoryA: string; categoryB: string } {
  const ruleType =
    seed.ruleType ?? deriveRuleType(seed.operandAKind, seed.operandBKind);
  return {
    ...seed,
    ruleType,
    categoryA: seed.operandAValue,
    categoryB: seed.operandBValue,
  };
}

export const COMPATIBILITY_RULE_SEED = [
  rule({
    code: "ACID_BASE_GROUP",
    operandAKind: "group",
    operandAValue: "STRONG_ACID",
    operandBKind: "group",
    operandBValue: "STRONG_BASE",
    categoryALabel: "Acid mạnh",
    categoryBLabel: "Base mạnh",
    severity: "critical",
    title: "Acid mạnh + Base mạnh — trung hòa mạnh",
    message:
      "Phản ứng trung hòa mạnh, sinh nhiều nhiệt và có thể bắn tóe dung dịch ăn mòn.",
    storageGuidance:
      "Không lưu chung. Tách riêng khu acid và khu base; dùng khay chắn thứ cấp.",
    examples: ["HCl + NaOH", "H2SO4 + NaOH", "TFA + triethylamine"],
  }),
  rule({
    code: "OXIDIZER_REDUCING_AGENT_GROUP",
    operandAKind: "group",
    operandAValue: "OXIDIZER",
    operandBKind: "group",
    operandBValue: "REDUCING_AGENT",
    categoryALabel: "Chất oxy hóa",
    categoryBLabel: "Chất khử",
    severity: "critical",
    title: "Chất oxy hóa + chất khử — phản ứng oxy hóa-khử",
    message:
      "Chất oxy hóa và chất khử phản ứng mạnh, có thể bốc cháy, nổ hoặc sinh khí độc.",
    storageGuidance: "Tách tuyệt đối chất oxy hóa và chất khử; không lưu chung tủ.",
    examples: ["KMnO4 + Fe powder", "H2O2 + metal powder", "KNO3 + sulfur"],
  }),
  rule({
    code: "OXIDIZER_FLAMMABLE_GROUP",
    operandAKind: "group",
    operandAValue: "OXIDIZER",
    operandBKind: "group",
    operandBValue: "FLAMMABLE_LIQUID",
    categoryALabel: "Chất oxy hóa",
    categoryBLabel: "Dung môi dễ cháy",
    severity: "high",
    title: "Chất oxy hóa + dung môi dễ cháy — nguy cơ cháy",
    message: "Chất oxy hóa có thể làm bùng cháy dung môi hữu cơ dễ cháy.",
    storageGuidance: "Giữ chất oxy hóa xa khu lưu dung môi dễ cháy.",
    examples: ["H2O2 + ethanol", "KNO3 + methanol"],
  }),
  rule({
    code: "OXIDIZER_ORGANIC_GROUP",
    operandAKind: "group",
    operandAValue: "OXIDIZER",
    operandBKind: "group",
    operandBValue: "ORGANIC_SOLVENT",
    categoryALabel: "Chất oxy hóa",
    categoryBLabel: "Dung môi hữu cơ",
    severity: "high",
    title: "Chất oxy hóa + hợp chất hữu cơ",
    message: "Chất oxy hóa mạnh phản ứng mạnh với nhiều hợp chất hữu cơ.",
    storageGuidance: "Tách chất oxy hóa khỏi mọi hóa chất hữu cơ.",
    examples: ["KMnO4 + toluene", "H2O2 + acetonitrile"],
  }),
  rule({
    code: "ACID_CYANIDE_GROUP",
    operandAKind: "group",
    operandAValue: "ACID",
    operandBKind: "group",
    operandBValue: "CYANIDE",
    categoryALabel: "Acid",
    categoryBLabel: "Cyanide",
    severity: "critical",
    title: "Acid + cyanide — khí HCN",
    message: "Acid giải phóng khí hydrocyanic (HCN) cực độc từ muối cyanide.",
    storageGuidance: "Cyanide trong tủ độc khóa, không cạnh acid.",
    examples: ["H2SO4 + NaCN", "HCl + KCN"],
  }),
  rule({
    code: "ACID_SULFIDE_GROUP",
    operandAKind: "group",
    operandAValue: "ACID",
    operandBKind: "group",
    operandBValue: "SULFIDE",
    categoryALabel: "Acid",
    categoryBLabel: "Sulfide",
    severity: "critical",
    title: "Acid + sulfide — khí H₂S",
    message: "Acid với sulfide sinh khí hydrogen sulfide (H2S) độc.",
    storageGuidance: "Tách sulfide khỏi acid; thông gió tốt.",
    examples: ["HCl + Na2S", "H2SO4 + iron sulfide"],
  }),
  rule({
    code: "WATER_REACTIVE_WATER_GROUP",
    operandAKind: "group",
    operandAValue: "WATER_REACTIVE",
    operandBKind: "group",
    operandBValue: "WATER",
    categoryALabel: "Phản ứng với nước",
    categoryBLabel: "Nước",
    severity: "critical",
    title: "Phản ứng với nước + dung dịch aqueous",
    message: "Hóa chất phản ứng với nước có thể bốc cháy hoặc giải phóng khí độc.",
    storageGuidance: "Giữ khô hoàn toàn, tách khỏi dung dịch chứa nước.",
    examples: ["Mg powder + water", "Acid chlorides + moisture"],
  }),
  rule({
    code: "PYROPHORIC_AIR_GROUP",
    operandAKind: "group",
    operandAValue: "PYROPHORIC",
    operandBKind: "group",
    operandBValue: "AIR",
    categoryALabel: "Pyrophoric",
    categoryBLabel: "Không khí / oxy",
    severity: "critical",
    title: "Pyrophoric + không khí — tự bốc cháy",
    message: "Hóa chất pyrophoric có thể tự bốc cháy khi tiếp xúc oxy trong không khí.",
    storageGuidance: "Bảo quản dưới khí trơ (N2/Ar); không mở ngoài tủ/glove box.",
    examples: ["White phosphorus + air", "Alkyl lithium + moisture/air"],
  }),
  rule({
    code: "ACID_BASE_HAZARD",
    operandAKind: "hazard",
    operandAValue: "ACID",
    operandBKind: "hazard",
    operandBValue: "BASE",
    categoryALabel: "Acid",
    categoryBLabel: "Base",
    severity: "critical",
    title: "Acid + Base — trung hòa exotherm",
    message:
      "Phản ứng trung hòa sinh nhiệt; có thể bắn tóe dung dịch ăn mòn.",
    storageGuidance: "Tách acid và base trong tủ riêng có khay chắn.",
    examples: ["HCl + NaOH", "H2SO4 + KOH"],
  }),
  rule({
    code: "NITRIC_ORGANIC",
    operandAKind: "cas",
    operandAValue: "7697-37-2",
    operandBKind: "hazard",
    operandBValue: "ORGANIC_SOLVENT",
    categoryALabel: "Acid nitric",
    categoryBLabel: "Dung môi hữu cơ",
    severity: "critical",
    title: "Acid nitric + dung môi hữu cơ — nit hóa / cháy",
    message:
      "Acid nitric phản ứng nguy hiểm với dung môi hữu cơ, sinh khí NOx độc và có thể bốc cháy.",
    storageGuidance: "Tủ acid riêng; không lưu HNO3 cùng dung môi hữu cơ.",
    examples: ["HNO3 + acetone", "HNO3 + ethanol", "HNO3 + toluene"],
  }),
  rule({
    code: "PERCHLORIC_ORGANIC",
    operandAKind: "cas",
    operandAValue: "7601-90-3",
    operandBKind: "hazard",
    operandBValue: "ORGANIC_SOLVENT",
    categoryALabel: "Acid perchloric",
    categoryBLabel: "Dung môi hữu cơ",
    severity: "critical",
    title: "Acid perchloric + dung môi hữu cơ — nổ / cháy",
    message:
      "Acid perchloric với hữu cơ tạo perchlorate dễ nổ; phản ứng exotherm cực mạnh.",
    storageGuidance: "Tủ acid chuyên dụng; không lưu cạnh hữu cơ và kim loại.",
    examples: ["HClO4 + methanol", "HClO4 + acetone"],
  }),
  rule({
    code: "CHROMIC_ORGANIC",
    operandAKind: "cas",
    operandAValue: "7732-88-5",
    operandBKind: "hazard",
    operandBValue: "ORGANIC_SOLVENT",
    categoryALabel: "Acid chromic",
    categoryBLabel: "Dung môi hữu cơ / alcohol",
    severity: "high",
    title: "Acid chromic + alcohol / hữu cơ — phản ứng mạnh",
    message:
      "Acid chromic với alcohol hoặc dung môi hữu cơ có thể phản ứng exotherm và tăng nguy cơ cháy.",
    storageGuidance: "Tách acid chromic khỏi alcohol và dung môi hữu cơ.",
    examples: ["Chromic acid + ethanol", "K2Cr2O7/H2SO4 + methanol"],
  }),
  rule({
    code: "H2O2_ORGANIC",
    operandAKind: "cas",
    operandAValue: "7722-84-1",
    operandBKind: "hazard",
    operandBValue: "ORGANIC_SOLVENT",
    categoryALabel: "Hydrogen peroxide",
    categoryBLabel: "Dung môi hữu cơ",
    severity: "high",
    title: "Hydrogen peroxide + hữu cơ — phản ứng oxy hóa",
    message: "H2O2 đậm đặc phản ứng mạnh với dung môi hữu cơ; có thể bốc cháy hoặc phân hủy bạo liệt.",
    storageGuidance: "Tách H2O2 khỏi alcohol, acetone và dung môi hữu cơ.",
    examples: ["H2O2 + ethanol", "H2O2 + acetonitrile"],
  }),
  rule({
    code: "KMnO4_ORGANIC",
    operandAKind: "cas",
    operandAValue: "7722-64-7",
    operandBKind: "hazard",
    operandBValue: "FLAMMABLE_LIQUID",
    categoryALabel: "Potassium permanganate",
    categoryBLabel: "Dung môi dễ cháy",
    severity: "high",
    title: "KMnO4 + dung môi dễ cháy — nguy cơ cháy",
    message: "KMnO4 là chất oxy hóa mạnh, có thể đốt cháy dung môi hữu cơ dễ cháy.",
    storageGuidance: "Giữ permanganate xa khu dung môi dễ cháy.",
    examples: ["KMnO4 + methanol", "KMnO4 + acetone"],
  }),
  rule({
    code: "OXIDIZER_FLAMMABLE",
    operandAKind: "hazard",
    operandAValue: "OXIDIZER",
    operandBKind: "hazard",
    operandBValue: "FLAMMABLE_LIQUID",
    categoryALabel: "Chất oxy hóa",
    categoryBLabel: "Dung môi dễ cháy",
    severity: "high",
    title: "Chất oxy hóa + dung môi dễ cháy — nguy cơ cháy",
    message: "Chất oxy hóa có thể làm bùng cháy dung môi hữu cơ dễ cháy.",
    storageGuidance: "Giữ chất oxy hóa xa khu lưu dung môi dễ cháy.",
    examples: ["H2O2 + ethanol", "KNO3 + methanol"],
  }),
  rule({
    code: "OXIDIZER_ORGANIC",
    operandAKind: "hazard",
    operandAValue: "OXIDIZER",
    operandBKind: "hazard",
    operandBValue: "ORGANIC_SOLVENT",
    categoryALabel: "Chất oxy hóa",
    categoryBLabel: "Dung môi hữu cơ",
    severity: "high",
    title: "Chất oxy hóa + hợp chất hữu cơ",
    message: "Chất oxy hóa mạnh phản ứng mạnh với nhiều hợp chất hữu cơ.",
    storageGuidance: "Tách chất oxy hóa khỏi mọi hóa chất hữu cơ.",
    examples: ["KMnO4 + toluene", "H2O2 + acetonitrile"],
  }),
  rule({
    code: "REACTIVE_METAL_WATER",
    operandAKind: "hazard",
    operandAValue: "REACTIVE_METAL",
    operandBKind: "hazard",
    operandBValue: "WATER",
    categoryALabel: "Kim loại hoạt động",
    categoryBLabel: "Nước",
    severity: "critical",
    title: "Kim loại hoạt động + nước — sinh khí H₂",
    message:
      "Kim loại kiềm/kiềm thổ phản ứng với nước, giải phóng khí hydro dễ cháy.",
    storageGuidance: "Bảo quản dưới dầu khoáng, xa nguồn nước.",
    examples: ["Na + H2O", "K + H2O"],
  }),
  rule({
    code: "WATER_REACTIVE_WATER",
    operandAKind: "hazard",
    operandAValue: "WATER_REACTIVE",
    operandBKind: "hazard",
    operandBValue: "WATER",
    categoryALabel: "Phản ứng với nước",
    categoryBLabel: "Nước",
    severity: "high",
    title: "Phản ứng với nước + dung dịch aqueous",
    message: "Hóa chất phản ứng với nước có thể bốc cháy hoặc giải phóng khí độc.",
    storageGuidance: "Giữ khô hoàn toàn, tách khỏi dung dịch chứa nước.",
    examples: ["Mg powder + water", "Acid chlorides + moisture"],
  }),
  rule({
    code: "ACID_OXIDIZER",
    operandAKind: "hazard",
    operandAValue: "ACID",
    operandBKind: "hazard",
    operandBValue: "OXIDIZER",
    categoryALabel: "Acid",
    categoryBLabel: "Chất oxy hóa",
    severity: "medium",
    title: "Acid + chất oxy hóa",
    message: "Acid mạnh kết hợp chất oxy hóa làm tăng độ ăn mòn và nguy cơ phân hủy.",
    storageGuidance: "Không xếp acid đặc ngay trên kệ chất oxy hóa.",
    examples: ["H2SO4 + H2O2", "HNO3 + H2O2"],
  }),
  rule({
    code: "BASE_OXIDIZER",
    operandAKind: "hazard",
    operandAValue: "BASE",
    operandBKind: "hazard",
    operandBValue: "OXIDIZER",
    categoryALabel: "Base",
    categoryBLabel: "Chất oxy hóa",
    severity: "medium",
    title: "Base + chất oxy hóa",
    message: "Base có thể làm tăng tốc phân hủy một số chất oxy hóa.",
    storageGuidance: "Tách base khỏi peroxide và muối oxy hóa.",
    examples: ["NaOH + H2O2", "KOH + KMnO4"],
  }),
  rule({
    code: "ACID_CYANIDE",
    operandAKind: "hazard",
    operandAValue: "ACID",
    operandBKind: "hazard",
    operandBValue: "CYANIDE",
    categoryALabel: "Acid",
    categoryBLabel: "Cyanide",
    severity: "critical",
    title: "Acid + cyanide — khí HCN",
    message: "Acid giải phóng khí hydrocyanic (HCN) cực độc từ muối cyanide.",
    storageGuidance: "Cyanide trong tủ độc khóa, không cạnh acid.",
    examples: ["H2SO4 + NaCN", "HCl + KCN"],
  }),
  rule({
    code: "AZIDE_ACID",
    operandAKind: "cas",
    operandAValue: "26628-22-8",
    operandBKind: "hazard",
    operandBValue: "ACID",
    categoryALabel: "Sodium azide",
    categoryBLabel: "Acid",
    severity: "critical",
    title: "Sodium azide + acid — khí độc",
    message:
      "Axit với sodium azide có thể giải phóng khí hydrazoic (HN3) — cực nguy hiểm.",
    storageGuidance: "Khóa riêng azide; tách xa mọi acid.",
    examples: ["NaN3 + HCl", "NaN3 + H2SO4"],
  }),
  rule({
    code: "ACID_SULFIDE",
    operandAKind: "hazard",
    operandAValue: "ACID",
    operandBKind: "hazard",
    operandBValue: "SULFIDE",
    categoryALabel: "Acid",
    categoryBLabel: "Sulfide",
    severity: "critical",
    title: "Acid + sulfide — khí H₂S",
    message: "Acid với sulfide sinh khí hydrogen sulfide (H2S) độc.",
    storageGuidance: "Tách sulfide khỏi acid; thông gió tốt.",
    examples: ["HCl + Na2S", "H2SO4 + iron sulfide"],
  }),
  rule({
    code: "HALOGENATED_ALKALI",
    operandAKind: "hazard",
    operandAValue: "HALOGENATED_SOLVENT",
    operandBKind: "hazard",
    operandBValue: "BASE",
    categoryALabel: "Dung môi halogen",
    categoryBLabel: "Base",
    severity: "high",
    title: "Dung môi halogen + base mạnh",
    message: "Base có thể phân hủy dung môi halogen thành phosgene và sản phẩm độc.",
    storageGuidance: "Không để DCM/chloroform cạnh base mạnh.",
    examples: ["DCM + NaOH", "Chloroform + KOH"],
  }),
  rule({
    code: "ORGANIC_PEROXIDE_ORGANIC",
    operandAKind: "hazard",
    operandAValue: "ORGANIC_PEROXIDE",
    operandBKind: "hazard",
    operandBValue: "ORGANIC_SOLVENT",
    categoryALabel: "Peroxide",
    categoryBLabel: "Dung môi hữu cơ",
    severity: "high",
    title: "Peroxide + dung môi hữu cơ",
    message: "Peroxide đặc hoặc dung môi dễ tạo peroxide có thể nổ khi nhiễm bẩn.",
    storageGuidance: "Theo dõi peroxide; tách H2O2 khỏi ether/THF cũ.",
    examples: ["H2O2 + diethyl ether", "Old THF + oxidizer"],
  }),
  rule({
    code: "AMMONIA_BLEACH",
    operandAKind: "hazard",
    operandAValue: "AMMONIA",
    operandBKind: "hazard",
    operandBValue: "OXIDIZER",
    categoryALabel: "Ammonia",
    categoryBLabel: "Chất oxy hóa",
    severity: "high",
    title: "Ammonia + chất oxy hóa — khí độc",
    message: "Ammonium với oxidizer có thể sinh khí chloramine độc.",
    storageGuidance: "Tách muối ammonium khỏi oxidizer.",
    examples: ["NH4Ac + H2O2", "Ammonia + bleach"],
  }),
  rule({
    code: "HYPOCHLORITE_ACID",
    operandAKind: "hazard",
    operandAValue: "HYPOCHLORITE",
    operandBKind: "hazard",
    operandBValue: "ACID",
    categoryALabel: "Bleach / hypochlorite",
    categoryBLabel: "Acid",
    severity: "critical",
    title: "Bleach + acid — khí Cl₂",
    message: "Trộn hypochlorite với acid giải phóng khí clo (Cl2) độc.",
    storageGuidance: "Không trộn bleach với acid.",
    examples: ["NaOCl + HCl", "Bleach + acetic acid"],
  }),
  rule({
    code: "HYPOCHLORITE_AMMONIA",
    operandAKind: "hazard",
    operandAValue: "HYPOCHLORITE",
    operandBKind: "hazard",
    operandBValue: "AMMONIA",
    categoryALabel: "Bleach / hypochlorite",
    categoryBLabel: "Ammonia",
    severity: "critical",
    title: "Bleach + ammonia — khí độc",
    message: "Bleach với ammonia sinh chloramine và có thể tạo NCl3.",
    storageGuidance: "Không bao giờ trộn bleach với ammonia.",
    examples: ["Household bleach + NH3"],
  }),
  rule({
    code: "FLAMMABLE_ACID",
    operandAKind: "hazard",
    operandAValue: "FLAMMABLE_LIQUID",
    operandBKind: "hazard",
    operandBValue: "ACID",
    categoryALabel: "Dung môi dễ cháy",
    categoryBLabel: "Acid",
    severity: "medium",
    title: "Dung môi dễ cháy + acid",
    message: "Trộn exotherm có thể làm bay hơi dung môi dễ cháy.",
    storageGuidance: "Khay chắn riêng; acid dưới kệ dung môi có thông gió.",
    examples: ["Methanol + HCl", "Isopropanol + formic acid"],
  }),
  rule({
    code: "TOXIC_OXIDIZER",
    operandAKind: "hazard",
    operandAValue: "TOXIC",
    operandBKind: "hazard",
    operandBValue: "OXIDIZER",
    categoryALabel: "Độc hại",
    categoryBLabel: "Chất oxy hóa",
    severity: "medium",
    title: "Độc hại + chất oxy hóa",
    message: "Oxidizer có thể làm tăng độc tính hoặc tạo sản phẩm phân hủy.",
    storageGuidance: "Tủ độc tách khỏi kệ oxidizer.",
    examples: ["Acetonitrile + H2O2"],
  }),
  rule({
    code: "SALT_WATER_REACTIVE",
    operandAKind: "hazard",
    operandAValue: "SALT",
    operandBKind: "hazard",
    operandBValue: "WATER_REACTIVE",
    categoryALabel: "Muối",
    categoryBLabel: "Phản ứng với nước",
    severity: "low",
    title: "Muối hút ẩm gần hóa chất phản ứng nước",
    message: "Muối hút ẩm có thể kích hoạt hàng xóm phản ứng với nước khi đổ.",
    storageGuidance: "Bảo quản khô; đậy kín container.",
    examples: ["NaCl dust + magnesium"],
  }),
];

export type CompatibilityRuleSeedRow = (typeof COMPATIBILITY_RULE_SEED)[number];
