import type { MethodSeedDefinition } from "./types";

export const METHOD_ICP_WATER: MethodSeedDefinition = {
  methodCode: "PP-ICP-WAT-001",
  methodName: "Xác định kim loại nặng trong nước uống bằng ICP-OES",
  matrix: "Water (Nước uống / nước thải đã qua lọc)",
  analyte: "Pb, Cd, As, Hg, Cr, Ni, Cu, Zn",
  technique: "ICP-OES",
  standardRef: "Tham chiếu EPA 200.7, SMEWW 3125 B, ISO 11885 (lab adaptation)",
  estimatedDurationMinutes: 180,
  sopMarkdown: `## Phạm vi (Scope)
Xác định hàm lượng Pb, Cd, As, Hg, Cr, Ni, Cu, Zn trong mẫu nước uống, nước ngầm và nước thải đã qua lọc sơ bộ. Phương pháp áp dụng cho phòng thí nghiệm kiểm soát chất lượng nước nội bộ.

## Nguyên lý (Principle)
Mẫu được acid hóa để chuyển kim loại sang dạng hòa tan, sau đó đưa vào plasma ICP-OES. Cường độ phát quang tại bước sóng đặc trưng của từng nguyên tố được so sánh với dãy chuẩn để tính nồng độ.

## Chuẩn bị mẫu (Sample preparation)
Lắc đồng nhất mẫu → lấy 50 mL aliquot → thêm HNO3 trace metal grade (2% v/v) → đun 95°C trong 2 giờ trong tủ hút → làm nguội → định mức 100 mL bằng nước Type I → lọc 0.45 µm nếu có cặn.

## Tóm tắt SOP
Phương pháp sử dụng ICP-OES Avio 500 với chế độ axial. Chuỗi phân tích gồm method blank, ICV, CCV và duplicate theo tần suất QC nội bộ. Kết quả báo cáo µg/L sau hiệu chỉnh blank và nội suy dãy chuẩn đa nguyên tố.`,
  layoutJson: JSON.stringify({ x: 0, y: 0, zoom: 0.85 }),
  nodes: [
    { nodeKey: "start", type: "Start", label: "Bắt đầu", description: "", positionX: 400, positionY: 0, configJson: "{}" },
    {
      nodeKey: "recv_sample",
      type: "Step",
      label: "Tiếp nhận mẫu",
      description: "Ghi nhận mã mẫu, thời gian lấy, nhiệt độ bảo quản",
      positionX: 400,
      positionY: 80,
      configJson: '{"category":"sample"}',
    },
    {
      nodeKey: "check_storage",
      type: "Step",
      label: "Kiểm tra bảo quản",
      description: "pH, nhiệt độ, thời hạn bảo quản ≤ 4°C / 24h",
      positionX: 400,
      positionY: 160,
      configJson: '{"category":"sample"}',
    },
    {
      nodeKey: "homogenize",
      type: "Step",
      label: "Lắc đồng nhất",
      description: "Lắc tay hoặc vortex 30 s",
      positionX: 400,
      positionY: 240,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "take_aliquot",
      type: "Step",
      label: "Lấy aliquot",
      description: "50 mL vào cốc PP đã sạch",
      positionX: 400,
      positionY: 320,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "acid_digest",
      type: "Step",
      label: "Acid hóa / tiêu hủy",
      description: "Thêm HNO3 2%, đun 95°C 2h trong tủ hút",
      positionX: 400,
      positionY: 400,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "hno3_reagent",
      type: "Reagent",
      label: "HNO3 trace metal",
      description: "5 mL HNO3 65% / mẫu",
      positionX: 620,
      positionY: 400,
      configJson: "{}",
    },
    {
      nodeKey: "cool_down",
      type: "Step",
      label: "Làm nguội",
      description: "Để nguội RT, rửa nắp",
      positionX: 400,
      positionY: 480,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "dilute",
      type: "Step",
      label: "Định mức",
      description: "Định mức 100 mL bằng nước Type I",
      positionX: 400,
      positionY: 560,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "filter",
      type: "Step",
      label: "Lọc nếu cần",
      description: "Lọc 0.45 µm nếu có cặn/huyền phù",
      positionX: 400,
      positionY: 640,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "cal_prep",
      type: "Step",
      label: "Chuẩn bị calibration",
      description: "Dãy chuẩn 5 điểm + ICV/CCV",
      positionX: 400,
      positionY: 720,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "run_blank_qc",
      type: "Qc",
      label: "Chạy blank / QC",
      description: "Method blank, ICV, CCV trước mẫu",
      positionX: 400,
      positionY: 800,
      configJson: "{}",
    },
    {
      nodeKey: "run_icp",
      type: "Equipment",
      label: "Chạy mẫu ICP-OES",
      description: "Avio 500 — chế độ axial, RF 1500 W",
      positionX: 400,
      positionY: 880,
      configJson: "{}",
    },
    {
      nodeKey: "qc_check",
      type: "Condition",
      label: "QC pass?",
      description: "Kiểm tra blank, recovery ICV/CCV, duplicate",
      positionX: 400,
      positionY: 960,
      configJson: '{"branches":["pass","fail"]}',
    },
    {
      nodeKey: "qc_fail_action",
      type: "Step",
      label: "Xử lý QC fail",
      description: "Lặp chạy QC; nếu vẫn fail → điều tra / chuẩn bị lại mẫu",
      positionX: 620,
      positionY: 1040,
      configJson: '{"category":"preparation","action":"repeat_or_reprepare"}',
    },
    {
      nodeKey: "calc_results",
      type: "Step",
      label: "Tính kết quả",
      description: "Hiệu chuẩn nội suy, trừ blank, báo cáo µg/L",
      positionX: 400,
      positionY: 1120,
      configJson: '{"category":"calculation"}',
    },
    {
      nodeKey: "approve_results",
      type: "Step",
      label: "Duyệt kết quả",
      description: "Lab manager / QAQC review và ký",
      positionX: 400,
      positionY: 1200,
      configJson: '{"category":"approval"}',
    },
    { nodeKey: "end", type: "End", label: "Kết thúc", description: "", positionX: 400, positionY: 1280, configJson: "{}" },
  ],
  edges: [
    { sourceNodeKey: "start", targetNodeKey: "recv_sample" },
    { sourceNodeKey: "recv_sample", targetNodeKey: "check_storage" },
    { sourceNodeKey: "check_storage", targetNodeKey: "homogenize" },
    { sourceNodeKey: "homogenize", targetNodeKey: "take_aliquot" },
    { sourceNodeKey: "take_aliquot", targetNodeKey: "acid_digest" },
    { sourceNodeKey: "acid_digest", targetNodeKey: "cool_down" },
    { sourceNodeKey: "cool_down", targetNodeKey: "dilute" },
    { sourceNodeKey: "dilute", targetNodeKey: "filter" },
    { sourceNodeKey: "filter", targetNodeKey: "cal_prep" },
    { sourceNodeKey: "cal_prep", targetNodeKey: "run_blank_qc" },
    { sourceNodeKey: "run_blank_qc", targetNodeKey: "run_icp" },
    { sourceNodeKey: "run_icp", targetNodeKey: "qc_check" },
    {
      sourceNodeKey: "qc_check",
      targetNodeKey: "calc_results",
      label: "Đạt",
      conditionJson: '{"result":"pass"}',
    },
    {
      sourceNodeKey: "qc_check",
      targetNodeKey: "qc_fail_action",
      label: "Không đạt",
      conditionJson: '{"result":"fail"}',
    },
    {
      sourceNodeKey: "qc_fail_action",
      targetNodeKey: "acid_digest",
      label: "Chuẩn bị lại",
      conditionJson: '{"action":"reprepare"}',
    },
    { sourceNodeKey: "calc_results", targetNodeKey: "approve_results" },
    { sourceNodeKey: "approve_results", targetNodeKey: "end" },
  ],
  reagents: [
    {
      nameFreeText: "Nitric acid 65% (trace metal grade)",
      chemicalCode: "CHEM-0030",
      casNumber: "7697-37-2",
      amountPerSample: 5,
      unit: "mL",
      workflowNodeKey: "hno3_reagent",
    },
    {
      nameFreeText: "Nước Type I",
      chemicalCode: "CHEM-0009",
      casNumber: "7732-18-5",
      amountPerSample: 50,
      unit: "mL",
      workflowNodeKey: "dilute",
    },
    {
      nameFreeText: "Dung dịch chuẩn đa nguyên tố ICP",
      casNumber: "",
      amountPerSample: 1,
      unit: "mL",
      workflowNodeKey: "cal_prep",
    },
    {
      nameFreeText: "Lead Standard 1000 mg/L",
      standardCode: "STD-0011",
      casNumber: "7439-92-1",
      amountPerSample: 0.1,
      unit: "mL",
      workflowNodeKey: "cal_prep",
    },
    {
      nameFreeText: "Syringe filter PTFE 0.45 µm",
      amountPerSample: 1,
      unit: "cái",
      isConsumable: true,
      workflowNodeKey: "filter",
    },
  ],
  equipment: [
    { equipmentCode: "EQ-ICP-001", role: "ICP-OES chính", workflowNodeKey: "run_icp" },
    { equipmentCode: "EQ-BAL-001", role: "Cân mẫu/aliquot", workflowNodeKey: "take_aliquot" },
    { equipmentCode: "EQ-HOOD-001", role: "Acid hóa trong tủ hút", workflowNodeKey: "acid_digest" },
    { equipmentCode: "EQ-VORT-001", role: "Lắc đồng nhất", workflowNodeKey: "homogenize" },
  ],
  qcRequirements: [
    {
      qcType: "Method Blank",
      frequency: "1",
      frequencyUnit: "lô",
      limitsJson: { maxSignalRatio: 0.05 },
    },
    {
      qcType: "CCV",
      frequency: "10",
      frequencyUnit: "mẫu",
      limitsJson: { recoveryMin: 85, recoveryMax: 115 },
    },
    {
      qcType: "ICV",
      frequency: "1",
      frequencyUnit: "chuỗi",
      limitsJson: { recoveryMin: 90, recoveryMax: 110 },
    },
    {
      qcType: "Duplicate",
      frequency: "20",
      frequencyUnit: "mẫu",
      limitsJson: { maxRpdPercent: 20 },
    },
  ],
  acceptanceCriteria: [
    { analyte: "Pb", criteriaJson: { unit: "µg/L", lod: 0.5, loq: 1.5, reportingLimit: 2.0, maxAllowed: 10 } },
    { analyte: "Cd", criteriaJson: { unit: "µg/L", lod: 0.1, loq: 0.3, reportingLimit: 0.5, maxAllowed: 3 } },
    { analyte: "As", criteriaJson: { unit: "µg/L", lod: 0.5, loq: 1.5, reportingLimit: 2.0, maxAllowed: 10 } },
    { analyte: "Hg", criteriaJson: { unit: "µg/L", lod: 0.05, loq: 0.15, reportingLimit: 0.2, maxAllowed: 1 } },
    { analyte: "Cr", criteriaJson: { unit: "µg/L", lod: 0.5, loq: 1.5, reportingLimit: 2.0, maxAllowed: 50 } },
    { analyte: "Ni", criteriaJson: { unit: "µg/L", lod: 0.5, loq: 1.5, reportingLimit: 2.0, maxAllowed: 20 } },
    { analyte: "Cu", criteriaJson: { unit: "µg/L", lod: 0.5, loq: 1.5, reportingLimit: 2.0, maxAllowed: 1000 } },
    { analyte: "Zn", criteriaJson: { unit: "µg/L", lod: 0.5, loq: 1.5, reportingLimit: 2.0, maxAllowed: 3000 } },
  ],
  safetyNotes: [
    {
      noteType: "Warning",
      content: "Acid nitric ăn mòn mạnh, sinh khí NOx khi đun. Bắt buộc tủ hút, găng chống acid, kính bảo vệ.",
      casNumber: "7697-37-2",
    },
    {
      noteType: "Toxic",
      content: "Thủy ngân độc tích lũy — tránh hít hơi và tiếp xúc da. Thu gom chất thải có Hg riêng.",
      casNumber: "7439-97-6",
    },
    {
      noteType: "Equipment",
      content: "Plasma ICP nhiệt độ và RF cao — không mở nắp khi đang chạy, tuân thủ SOP vận hành thiết bị.",
    },
  ],
};
