import type { MethodSeedDefinition } from "./types";

export const METHOD_LCMS_PESTICIDE: MethodSeedDefinition = {
  methodCode: "PP-LCMS-PST-001",
  methodName: "Xác định dư lượng Acetamiprid trong rau ăn lá bằng QuEChERS và LC-MS/MS",
  matrixCodes: ["FOOD-VEG"],
  testMethodCodes: ["PEST-LCMS"],
  analyte: "Acetamiprid",
  technique: "LC-MS/MS",
  standardRef: "Tham chiếu EN 15662, AOAC 2007.01 (QuEChERS), SANTE 11312/2021",
  estimatedDurationMinutes: 240,
  sopMarkdown: `## Phạm vi (Scope)
Xác định dư lượng Acetamiprid trong rau ăn lá tươi (cải xanh, rau muống, xà lách) phục vụ kiểm tra MRL nội bộ và đối chứng phương pháp.

## Nguyên lý (Principle)
Mẫu được đồng nhất hóa, chiết bằng acetonitrile/ethyl acetate theo QuEChERS, làm sạch bằng dSPE, sau đó phân tích bằng LC-MS/MS ở chế độ MRM. Nồng độ tính từ đường chuẩn ngoại suy.

## Chuẩn bị mẫu (Sample preparation)
Cân 10.0 ± 0.1 g mẫu đồng nhất → thêm chuẩn nội (nếu có) → chiết 10 mL ACN + 10 mL EtOAc → vortex 1 min + siêu âm 5 min → thêm muối QuEChERS (4 g MgSO4 + 1 g NaCl) → ly tâm → dSPE cleanup → lọc 0.22 µm vào vial LC.

## Tóm tắt SOP
Phương pháp QuEChERS kết hợp LC-MS/MS QTRAP 4500. QC gồm matrix blank, LCS, CCV và kiểm tra recovery chuẩn nội. Kết quả báo cáo mg/kg, so sánh MRL tham chiếu 0.5 mg/kg (EU).`,
  layoutJson: JSON.stringify({ x: 0, y: 0, zoom: 0.8 }),
  nodes: [
    { nodeKey: "start", type: "Start", label: "Bắt đầu", description: "", positionX: 400, positionY: 0, configJson: "{}" },
    {
      nodeKey: "recv_sample",
      type: "Step",
      label: "Tiếp nhận mẫu",
      description: "Rau tươi, ghi nguồn gốc",
      positionX: 400,
      positionY: 80,
      configJson: '{"category":"sample"}',
    },
    {
      nodeKey: "homogenize",
      type: "Step",
      label: "Đồng nhất mẫu",
      description: "Cắt nhỏ, homogenizer hoặc máy xay",
      positionX: 400,
      positionY: 160,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "weigh_sample",
      type: "Step",
      label: "Cân mẫu",
      description: "10.0 ± 0.1 g vào tube 50 mL",
      positionX: 400,
      positionY: 240,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "add_is",
      type: "Step",
      label: "Thêm chuẩn nội",
      description: "IS Acetamiprid-d3 nếu có trong batch",
      positionX: 400,
      positionY: 320,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "extract",
      type: "Step",
      label: "Chiết dung môi",
      description: "10 mL ACN + 10 mL EtOAc",
      positionX: 400,
      positionY: 400,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "shake_vortex",
      type: "Step",
      label: "Lắc / siêu âm",
      description: "Vortex 1 min + ultrasonication 5 min",
      positionX: 400,
      positionY: 480,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "quechers_salt",
      type: "Reagent",
      label: "Muối QuEChERS",
      description: "4 g MgSO4 + 1 g NaCl",
      positionX: 620,
      positionY: 480,
      configJson: "{}",
    },
    {
      nodeKey: "centrifuge",
      type: "Step",
      label: "Ly tâm",
      description: "4000 rpm, 5 min",
      positionX: 400,
      positionY: 560,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "dspe_clean",
      type: "Step",
      label: "Làm sạch dSPE",
      description: "PSA/C18 cleanup tube",
      positionX: 400,
      positionY: 640,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "filter",
      type: "Step",
      label: "Lọc 0.22 µm",
      description: "Syringe filter vào vial LC",
      positionX: 400,
      positionY: 720,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "cal_prep",
      type: "Step",
      label: "Pha chuẩn hiệu chuẩn",
      description: "Dãy 5 điểm 0.005–0.5 mg/L",
      positionX: 400,
      positionY: 800,
      configJson: '{"category":"preparation"}',
    },
    {
      nodeKey: "sys_suit",
      type: "Qc",
      label: "System suitability",
      description: "RSD ≤ 5%, S/N ≥ 10",
      positionX: 400,
      positionY: 880,
      configJson: "{}",
    },
    {
      nodeKey: "run_blank_qc",
      type: "Qc",
      label: "Chạy blank / QC",
      description: "Matrix blank, LCS, CCV",
      positionX: 400,
      positionY: 960,
      configJson: "{}",
    },
    {
      nodeKey: "run_lcms",
      type: "Equipment",
      label: "Chạy mẫu LC-MS/MS",
      description: "QTRAP 4500 — MRM transition",
      positionX: 400,
      positionY: 1040,
      configJson: "{}",
    },
    {
      nodeKey: "qc_check",
      type: "Condition",
      label: "QC pass?",
      description: "Recovery LCS 70–120%, CCV ±15%",
      positionX: 400,
      positionY: 1120,
      configJson: '{"branches":["pass","fail"]}',
    },
    {
      nodeKey: "qc_fail_action",
      type: "Step",
      label: "Xử lý QC fail",
      description: "Repeat injection hoặc chiết lại mẫu",
      positionX: 620,
      positionY: 1200,
      configJson: '{"category":"preparation","action":"repeat_or_reextract"}',
    },
    {
      nodeKey: "calc_results",
      type: "Step",
      label: "Tính kết quả",
      description: "Tính mg/kg, so MRL",
      positionX: 400,
      positionY: 1280,
      configJson: '{"category":"calculation"}',
    },
    {
      nodeKey: "approve_results",
      type: "Step",
      label: "Duyệt kết quả",
      description: "QAQC review và ký",
      positionX: 400,
      positionY: 1360,
      configJson: '{"category":"approval"}',
    },
    { nodeKey: "end", type: "End", label: "Kết thúc", description: "", positionX: 400, positionY: 1440, configJson: "{}" },
  ],
  edges: [
    { sourceNodeKey: "start", targetNodeKey: "recv_sample" },
    { sourceNodeKey: "recv_sample", targetNodeKey: "homogenize" },
    { sourceNodeKey: "homogenize", targetNodeKey: "weigh_sample" },
    { sourceNodeKey: "weigh_sample", targetNodeKey: "add_is" },
    { sourceNodeKey: "add_is", targetNodeKey: "extract" },
    { sourceNodeKey: "extract", targetNodeKey: "shake_vortex" },
    { sourceNodeKey: "shake_vortex", targetNodeKey: "centrifuge" },
    { sourceNodeKey: "centrifuge", targetNodeKey: "dspe_clean" },
    { sourceNodeKey: "dspe_clean", targetNodeKey: "filter" },
    { sourceNodeKey: "filter", targetNodeKey: "cal_prep" },
    { sourceNodeKey: "cal_prep", targetNodeKey: "sys_suit" },
    { sourceNodeKey: "sys_suit", targetNodeKey: "run_blank_qc" },
    { sourceNodeKey: "run_blank_qc", targetNodeKey: "run_lcms" },
    { sourceNodeKey: "run_lcms", targetNodeKey: "qc_check" },
    {
      sourceNodeKey: "qc_check",
      targetNodeKey: "calc_results",
      label: "Đạt",
      conditionJson: '{"result":"pass"}',
    },
    {
      sourceNodeKey: "qc_check",
      targetNodeKey: "qc_fail_action",
      label: "Không đạt",
      conditionJson: '{"result":"fail"}',
    },
    {
      sourceNodeKey: "qc_fail_action",
      targetNodeKey: "extract",
      label: "Chiết lại",
      conditionJson: '{"action":"reextract"}',
    },
    { sourceNodeKey: "calc_results", targetNodeKey: "approve_results" },
    { sourceNodeKey: "approve_results", targetNodeKey: "end" },
  ],
  reagents: [
    {
      nameFreeText: "Acetonitrile LC-MS",
      chemicalCode: "CHEM-0002",
      casNumber: "75-05-8",
      amountPerSample: 10,
      unit: "mL",
      workflowNodeKey: "extract",
    },
    {
      nameFreeText: "Ethyl acetate",
      chemicalCode: "CHEM-0014",
      casNumber: "141-78-6",
      amountPerSample: 10,
      unit: "mL",
      workflowNodeKey: "extract",
    },
    {
      nameFreeText: "MgSO4 anhydrous (QuEChERS)",
      chemicalCode: "CHEM-0016",
      casNumber: "7487-88-9",
      amountPerSample: 4,
      unit: "g",
      workflowNodeKey: "quechers_salt",
    },
    {
      nameFreeText: "NaCl",
      chemicalCode: "CHEM-0017",
      casNumber: "7647-14-5",
      amountPerSample: 1,
      unit: "g",
      workflowNodeKey: "quechers_salt",
    },
    {
      nameFreeText: "Formic acid",
      chemicalCode: "CHEM-0011",
      casNumber: "64-18-6",
      amountPerSample: 0.1,
      unit: "mL",
      workflowNodeKey: "cal_prep",
    },
    {
      nameFreeText: "Ammonium formate",
      chemicalCode: "CHEM-0029",
      casNumber: "540-69-2",
      amountPerSample: 0.05,
      unit: "g",
      workflowNodeKey: "cal_prep",
    },
    {
      nameFreeText: "Acetamiprid CRM 100 µg/mL",
      standardCode: "STD-0027",
      casNumber: "135410-20-7",
      amountPerSample: 0.01,
      unit: "mL",
      workflowNodeKey: "cal_prep",
    },
    {
      nameFreeText: "Syringe filter 0.22 µm",
      amountPerSample: 1,
      unit: "cái",
      isConsumable: true,
      workflowNodeKey: "filter",
    },
  ],
  equipment: [
    { equipmentCode: "EQ-LC-MS-001", role: "LC-MS/MS", workflowNodeKey: "run_lcms" },
    { equipmentCode: "EQ-BAL-002", role: "Cân mẫu 0.1 mg", workflowNodeKey: "weigh_sample" },
    { equipmentCode: "EQ-VORT-001", role: "Lắc vortex", workflowNodeKey: "shake_vortex" },
    { equipmentCode: "EQ-HOOD-001", role: "Chiết dung môi", workflowNodeKey: "extract" },
  ],
  qcRequirements: [
    {
      qcType: "Matrix Blank",
      frequency: "1",
      frequencyUnit: "lô",
      limitsJson: { maxPeakAreaRatio: 0.05 },
    },
    {
      qcType: "LCS",
      frequency: "1",
      frequencyUnit: "lô",
      limitsJson: { recoveryMin: 70, recoveryMax: 120 },
    },
    {
      qcType: "CCV",
      frequency: "5",
      frequencyUnit: "mẫu",
      limitsJson: { deviationMaxPercent: 15 },
    },
    {
      qcType: "IS Recovery",
      frequency: "1",
      frequencyUnit: "mẫu",
      limitsJson: { recoveryMin: 80, recoveryMax: 120 },
    },
  ],
  acceptanceCriteria: [
    {
      analyte: "Acetamiprid",
      criteriaJson: {
        unit: "mg/kg",
        lod: 0.005,
        loq: 0.01,
        mrlReference: 0.5,
        mrlSource: "EU MRL (vegetables)",
      },
    },
  ],
  safetyNotes: [
    {
      noteType: "Warning",
      content: "Acetonitrile dễ cháy — làm việc xa nguồn lửa, thông gió tốt trong tủ hút.",
      casNumber: "75-05-8",
    },
    {
      noteType: "Warning",
      content: "Ethyl acetate dễ cháy — không đun nóng trực tiếp, tránh tia lửa tĩnh điện.",
      casNumber: "141-78-6",
    },
    {
      noteType: "PPE",
      content: "Formic acid ăn mòn — đeo găng nitrile và kính bảo vệ khi pha mobile phase.",
      casNumber: "64-18-6",
    },
  ],
};
